spring:
  application:
    name: local-taskflow
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/taskflow_db?currentSchema=task
    username: postgres
    password: postgres