spring:
  application:
    name: docker-taskflow
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/taskflow_db?currentSchema=task
    username: postgres
    password: postgres