spring:
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 7600
  servlet:
    context-path: /tasks

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    operationsSorter: method
    tagsSorter: alpha
    enable-deep-linking: true
    show-extensions: true

  api-docs:
    path: /api-docs

management:
  endpoints:
    web:
      exposure:
        include: "health, info, metrics"
  endpoint:
    health:
      show-details: always

task:
  scheduler:
    delay: 60000

jwt:
  token:
    secret: ${SECRET}
    expiry: 900000