spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  token:
    secret: test-secret-key-for-tests-126-bit
    expiry: 360000

task:
  scheduler:
    delay: 1000